codecov:
  require_ci_to_pass: true

comment:
  layout: "reach, diff, files"
  behavior: default
  require_changes: false
  require_base: true
  require_head: true

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 100%
        base: auto
        if_not_found: success
        if_ci_failed: error
        informational: false
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 100%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
        only_pulls: false

github_checks:
  annotations: false
